### ISSUE TITLE
v1.4 compatibility recheck

### ISSUE THREAD

**Issue by Vectorial1024** [Vectorial1024/EliteBionicsFramework#40]
Thanks to the long peace in RW v1.3, a lot of extra "exported" dependency was added here and there. Now, with RW v1.4 available, and mods are updating, there is a need to review everything again.

This is the (hopefully complete) list of mods that require rechecking:

(Note: I marked some mods as "not yet v1.4", but they might just release a v1.4 update while I am not looking; check my last edit time to be sure.)

- [x] EdB Prepare Carefully
- [x] Humanoid Alien Races (HAR)
- [x] Moody
- [x] Callouts (special situation; see https://github.com/Vectorial1024/EliteBionicsFramework/issues/49)
- [x] Compact Hediffs
- [x] Half Dragons (v1.4+ maintained at https://steamcommunity.com/sharedfiles/filedetails/?id=2932034042)
- [ ] Save Our Ships 2 (SOS2) (#3) (not yet v1.4)
- [x] Cybernetic Organism and Neural Network (CONN) (#43)
- [x] Cyber Fauna
- [x] Level This! (https://steamcommunity.com/sharedfiles/filedetails/?id=2574042900)
- [x] Mechalit Core
- [x] Pawnmorpher
- [x] Quality Bionics
- [x] Vanilla Genetics Expanded
- [ ] (perhaps more...)

**Disclaimer**: this only reflects the compatibility of the GitHub unstable version. It is only an approximate indicator of how things are going.

**Comment by Vectorial1024** [comment]
This leaves SOS2 the only mod on this list that is not yet up to 1.4 due to the busy author + ongoing SOS2 rewrite.

**Comment by Vectorial1024** [comment]
...It has been nearly a year, and vanilla 1.5 is coming out soon.

It pains me, but perhaps we should consider dropping support for SOS2 until it comes back healthy and what not.

**Comment by Vectorial1024** [comment]
Update: RW 1.5 will be released on 11 April; SOS2 still haven't got any v1.4 support.

I shall conclude that the v1.4 update recheck is finally complete.
