### ISSUE TITLE
v1.5 compatibility recheck

### ISSUE THREAD

**Issue by Vectorial1024** [Vectorial1024/EliteBionicsFramework#75]
Thanks to the long peace in RW v1.4 (we are noticing the Ludeon style now), compatibility was mostly not a problem (See https://github.com/Vectorial1024/EliteBionicsFramework/issues/40 ). Now, with RW v1.5 coming out soon, and mods are updating, there is a need to review everything again.

This is the (hopefully complete) list of mods that require rechecking:

(Note: the mods might just release a v1.5 update while I am not looking; check my last edit time to be sure.)

- [x] EdB Prepare Carefully (see 36f239fc5f6ab0d8986ebaccf208878fc21d257a)
- [x] Humanoid Alien Races (HAR)
- [x] Moody (also see #68)
- [x] Callouts (special situation; see #49)
- [x] Compact Hediffs
- [x] Half Dragons (update: see #86)
- [x] ~Cybernetic Organism and Neural Network (CONN)~ (no longer tracked; ref https://github.com/Vectorial1024/EliteBionicsFramework/issues/43#issuecomment-2059413129)
- [x] ~Cyber Fauna~ (special situation; see #81)
- [x] Level This! (intent to abandon; see #94)
- [x] ~Mechalit Core~ (special situation; see #81)
- [x] Pawnmorpher (related to #74)
- [x] Quality Bionics (special situation; see #79)
- [x] Vanilla Genetics Expanded
- [x] Altered Carbon: Ultratech Unleashed (#71)
- [x] ~Pawn Quick Info~ (no longer tracked; ref #73)
- [x] Neural Intercept Matrix (#76)
- [x] Vanilla Psycasts Extended (Requires Royalty, but no Royalty; assuming it works)
- [x] Immortals
- [ ] (perhaps more...)

~We are contemplating whether to drop support for~ ~We are dropping support of~ we are restoring support for:
- [x] Save Our Ships 2 (SOS2) (~see https://github.com/Vectorial1024/EliteBionicsFramework/issues/3~) (see #85)

**Comment by Vectorial1024** [comment]
Finally, all are done.
